name: Test with rspec

on: pull_request

env:
  FORCE_COLOR: 1
  POSTGRES_PASSWORD: postgres
  POSTGRES_USER: postgres
  POSTGRES_HOST: localhost
  RAILS_ENV: test

jobs:
  build:
    runs-on: ubuntu-latest
    services:
      db:
        image: postgres
        ports: 
          - 5432:5432
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: postgres
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-ruby@v1
        with:
          ruby-version: 2.6.x
        env:
          POSTGRES_HOST: 127.0.0.1
          POSTGRES_PORT: 5432
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: postgres
          RAILS_ENV: test
      - name: Run Tests
        run: | 
          sudo apt-get -yqq install libpq-dev 
          gem install bundler
          bundle install --jobs 4 --retry 3
          sudo service postgresql restart
          bundle exec rake db:create
          bundle exec rails db:migrate
          bundle exec rake